eureka:
  client:
    serviceUrl:
      defaultZone: http://eurekabook-container:8761/eureka/
server:
  port: 7071
spring:
  application:
    name: authordetails
  data:
    mongodb:
      uri: mongodb+srv://anagh11:anagh11@bookcluster.dl7kn.mongodb.net/?retryWrites=true&w=majority&appName=BookCluster
      database: bookdbauthor

